# Autogenerated wrapper script for ASAGI_jll for armv7l-linux-gnueabihf-cxx11-mpi+mpitrampoline
export libasagi

using CompilerSupportLibraries_jll
using HDF5_jll
using NetCDF_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("ASAGI")
JLLWrappers.@declare_library_product(libasagi, "libasagi.so.1")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HDF5_jll, NetCDF_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libasagi,
        "lib/libasagi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
