# Autogenerated wrapper script for ASAGI_jll for x86_64-w64-mingw32-cxx11-mpi+microsoftmpi
export libasagi

using CompilerSupportLibraries_jll
using HDF5_jll
using NetCDF_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("ASAGI")
JLLWrappers.@declare_library_product(libasagi, "libasagi.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HDF5_jll, NetCDF_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libasagi,
        "bin\\libasagi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
