# Autogenerated wrapper script for ASAGI_jll for x86_64-apple-darwin-mpi+mpich
export libasagi

using HDF5_jll
using LLVMOpenMP_jll
using NetCDF_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("ASAGI")
JLLWrappers.@declare_library_product(libasagi, "@rpath/libasagi.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, LLVMOpenMP_jll, NetCDF_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libasagi,
        "lib/libasagi.1.0.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
